import React from 'react';
import { EditorManager } from '../manager';
import { RegionConfig, RendererInfo } from '../plugin';
import { EditorStoreType } from '../store/editor';
import { EditorNodeType } from '../store/node';
export interface RegionWrapperProps {
    name: string;
    label: string;
    placeholder?: string | JSX.Element;
    preferTag?: string;
    wrapperResolve?: (dom: HTMLElement) => HTMLElement;
    editorStore: EditorStoreType;
    manager: EditorManager;
    rendererName?: string;
    regionConfig: RegionConfig;
    node?: EditorNodeType;
    $$editor?: RendererInfo;
    children?: React.ReactNode;
}
/**
 * 1.DOM标记 添加 data-region、data-region-host 和 data-renderer 属性
 * 2.构建 Node store 节点。
 */
export declare class RegionWrapper extends React.Component<RegionWrapperProps> {
    static contextType: React.Context<({
        parentId: string;
        parentRegion: string;
        isCommonConfig: boolean;
        id: string;
        type: string;
        label: string;
        regionInfo: (RegionConfig & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>>) | undefined;
        path: string;
        schemaPath: string;
        region: string;
        preferTag: string;
        state: any;
        widthMutable: boolean;
        heightMutable: boolean;
        memberIndex: number;
        folded: boolean;
        patched: boolean;
        x: number;
        y: number;
        w: number;
        h: number;
        dialogTitle: string;
        dialogType: string;
        children: import("mobx-state-tree").IMSTArray<import("mobx-state-tree").IAnyModelType> & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>>;
    } & import("mobx-state-tree/dist/internal").NonEmptyObject & {
        getData: import("mobx-state-tree").IType<() => any, () => any, () => any>;
    } & {
        readonly info: RendererInfo;
        getNodeById(id: string, regionOrType?: string | undefined): any;
        setInfo(value: RendererInfo): void;
        updateSharedContext(value: Record<string, any>): void;
        readonly rendererConfig: import("amis-core").RendererConfig | undefined;
        setRendererConfig(value: import("amis-core").RendererConfig): void;
        readonly isVitualRenderer: boolean;
        readonly clickable: boolean;
        readonly draggable: boolean;
        readonly moveable: boolean;
        readonly canMoveUp: boolean;
        readonly canMoveDown: boolean;
        readonly removable: boolean;
        readonly duplicatable: boolean;
        readonly replaceable: boolean;
        memberImmutable(region: string): boolean;
        readonly isRegion: boolean;
        readonly childRegions: any[];
        readonly uniqueChildren: any[];
        readonly sameIdChild: any;
        readonly singleRegion: boolean;
        isExists(id: string): boolean;
        getChildById(id: string): any;
        readonly parent: any;
        readonly ancestorField: any;
        readonly host: any;
        readonly firstChild: any;
        readonly index: any;
        readonly prevSibling: any;
        readonly nextSibling: any;
        readonly schema: any;
        readonly schemaParent: any;
        readonly isSecondFactor: boolean;
    } & {
        getClosestParentByType: (type: string) => void | ({
            parentId: string;
            parentRegion: string;
            isCommonConfig: boolean;
            id: string;
            type: string;
            label: string;
            regionInfo: (RegionConfig & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>>) | undefined;
            path: string;
            schemaPath: string;
            region: string;
            preferTag: string;
            state: any;
            widthMutable: boolean;
            heightMutable: boolean;
            memberIndex: number;
            folded: boolean;
            patched: boolean;
            x: number;
            y: number;
            w: number;
            h: number;
            dialogTitle: string;
            dialogType: string;
            children: import("mobx-state-tree").IMSTArray<import("mobx-state-tree").IAnyModelType> & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>>;
        } & import("mobx-state-tree/dist/internal").NonEmptyObject & {
            getData: import("mobx-state-tree").IType<() => any, () => any, () => any>;
        } & {
            readonly info: RendererInfo;
            getNodeById(id: string, regionOrType?: string | undefined): any;
            setInfo(value: RendererInfo): void;
            updateSharedContext(value: Record<string, any>): void;
            readonly rendererConfig: import("amis-core").RendererConfig | undefined;
            setRendererConfig(value: import("amis-core").RendererConfig): void;
            readonly isVitualRenderer: boolean;
            readonly clickable: boolean;
            readonly draggable: boolean;
            readonly moveable: boolean;
            readonly canMoveUp: boolean;
            readonly canMoveDown: boolean;
            readonly removable: boolean;
            readonly duplicatable: boolean;
            readonly replaceable: boolean;
            memberImmutable(region: string): boolean;
            readonly isRegion: boolean;
            readonly childRegions: any[];
            readonly uniqueChildren: any[];
            readonly sameIdChild: any;
            readonly singleRegion: boolean;
            isExists(id: string): boolean;
            getChildById(id: string): any;
            readonly parent: any;
            readonly ancestorField: any;
            readonly host: any;
            readonly firstChild: any;
            readonly index: any;
            readonly prevSibling: any;
            readonly nextSibling: any;
            readonly schema: any;
            readonly schemaParent: any;
            readonly isSecondFactor: boolean;
        } & any & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IModelType<{
            parentId: import("mobx-state-tree").IType<string | undefined, string, string>;
            parentRegion: import("mobx-state-tree").IType<string | undefined, string, string>;
            isCommonConfig: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            id: import("mobx-state-tree").IType<string | undefined, string, string>;
            type: import("mobx-state-tree").IType<string | undefined, string, string>;
            label: import("mobx-state-tree").IType<string | undefined, string, string>;
            regionInfo: import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>;
            path: import("mobx-state-tree").IType<string | undefined, string, string>;
            schemaPath: import("mobx-state-tree").IType<string | undefined, string, string>;
            region: import("mobx-state-tree").IType<string | undefined, string, string>;
            preferTag: import("mobx-state-tree").IType<string | undefined, string, string>;
            state: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IType<any, any, any>, [undefined]>;
            widthMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            heightMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            memberIndex: import("mobx-state-tree").IType<number | undefined, number, number>;
            folded: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            patched: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            x: import("mobx-state-tree").IType<number | undefined, number, number>;
            y: import("mobx-state-tree").IType<number | undefined, number, number>;
            w: import("mobx-state-tree").IType<number | undefined, number, number>;
            h: import("mobx-state-tree").IType<number | undefined, number, number>;
            dialogTitle: import("mobx-state-tree").IType<string | undefined, string, string>;
            dialogType: import("mobx-state-tree").IType<string | undefined, string, string>;
            children: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>;
        }, {
            getData: import("mobx-state-tree").IType<() => any, () => any, () => any>;
        } & {
            readonly info: RendererInfo;
            getNodeById(id: string, regionOrType?: string | undefined): any;
            setInfo(value: RendererInfo): void;
            updateSharedContext(value: Record<string, any>): void;
            readonly rendererConfig: import("amis-core").RendererConfig | undefined;
            setRendererConfig(value: import("amis-core").RendererConfig): void;
            readonly isVitualRenderer: boolean;
            readonly clickable: boolean;
            readonly draggable: boolean;
            readonly moveable: boolean;
            readonly canMoveUp: boolean;
            readonly canMoveDown: boolean;
            readonly removable: boolean;
            readonly duplicatable: boolean;
            readonly replaceable: boolean;
            memberImmutable(region: string): boolean;
            readonly isRegion: boolean;
            readonly childRegions: any[];
            readonly uniqueChildren: any[];
            readonly sameIdChild: any;
            readonly singleRegion: boolean;
            isExists(id: string): boolean;
            getChildById(id: string): any;
            readonly parent: any;
            readonly ancestorField: any;
            readonly host: any;
            readonly firstChild: any;
            readonly index: any;
            readonly prevSibling: any;
            readonly nextSibling: any;
            readonly schema: any;
            readonly schemaParent: any;
            readonly isSecondFactor: boolean;
        } & any, import("mobx-state-tree")._NotCustomized, import("mobx-state-tree")._NotCustomized>>);
        getParentNodeByCB: (callback: (node: import("mobx-state-tree").ModelCreationType<import("mobx-state-tree/dist/internal").ExtractCFromProps<{
            parentId: import("mobx-state-tree").IType<string | undefined, string, string>;
            parentRegion: import("mobx-state-tree").IType<string | undefined, string, string>;
            isCommonConfig: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            id: import("mobx-state-tree").IType<string | undefined, string, string>;
            type: import("mobx-state-tree").IType<string | undefined, string, string>;
            label: import("mobx-state-tree").IType<string | undefined, string, string>;
            regionInfo: import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>;
            path: import("mobx-state-tree").IType<string | undefined, string, string>;
            schemaPath: import("mobx-state-tree").IType<string | undefined, string, string>;
            region: import("mobx-state-tree").IType<string | undefined, string, string>;
            preferTag: import("mobx-state-tree").IType<string | undefined, string, string>;
            state: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IType<any, any, any>, [undefined]>;
            widthMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            heightMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            memberIndex: import("mobx-state-tree").IType<number | undefined, number, number>;
            folded: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            patched: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            x: import("mobx-state-tree").IType<number | undefined, number, number>;
            y: import("mobx-state-tree").IType<number | undefined, number, number>;
            w: import("mobx-state-tree").IType<number | undefined, number, number>;
            h: import("mobx-state-tree").IType<number | undefined, number, number>;
            dialogTitle: import("mobx-state-tree").IType<string | undefined, string, string>;
            dialogType: import("mobx-state-tree").IType<string | undefined, string, string>;
            children: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>;
        }>>) => Boolean) => {
            parentId: string;
            parentRegion: string;
            isCommonConfig: boolean;
            id: string;
            type: string;
            label: string;
            regionInfo: (RegionConfig & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>>) | undefined;
            path: string;
            schemaPath: string;
            region: string;
            preferTag: string;
            state: any;
            widthMutable: boolean;
            heightMutable: boolean;
            memberIndex: number;
            folded: boolean;
            patched: boolean;
            x: number;
            y: number;
            w: number;
            h: number;
            dialogTitle: string;
            dialogType: string;
            children: import("mobx-state-tree").IMSTArray<import("mobx-state-tree").IAnyModelType> & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>>;
        } & import("mobx-state-tree/dist/internal").NonEmptyObject & {
            getData: import("mobx-state-tree").IType<() => any, () => any, () => any>;
        } & {
            readonly info: RendererInfo;
            getNodeById(id: string, regionOrType?: string | undefined): any;
            setInfo(value: RendererInfo): void;
            updateSharedContext(value: Record<string, any>): void;
            readonly rendererConfig: import("amis-core").RendererConfig | undefined;
            setRendererConfig(value: import("amis-core").RendererConfig): void;
            readonly isVitualRenderer: boolean;
            readonly clickable: boolean;
            readonly draggable: boolean;
            readonly moveable: boolean;
            readonly canMoveUp: boolean;
            readonly canMoveDown: boolean;
            readonly removable: boolean;
            readonly duplicatable: boolean;
            readonly replaceable: boolean;
            memberImmutable(region: string): boolean;
            readonly isRegion: boolean;
            readonly childRegions: any[];
            readonly uniqueChildren: any[];
            readonly sameIdChild: any;
            readonly singleRegion: boolean;
            isExists(id: string): boolean;
            getChildById(id: string): any;
            readonly parent: any;
            readonly ancestorField: any;
            readonly host: any;
            readonly firstChild: any;
            readonly index: any;
            readonly prevSibling: any;
            readonly nextSibling: any;
            readonly schema: any;
            readonly schemaParent: any;
            readonly isSecondFactor: boolean;
        } & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IModelType<{
            parentId: import("mobx-state-tree").IType<string | undefined, string, string>;
            parentRegion: import("mobx-state-tree").IType<string | undefined, string, string>;
            isCommonConfig: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            id: import("mobx-state-tree").IType<string | undefined, string, string>;
            type: import("mobx-state-tree").IType<string | undefined, string, string>;
            label: import("mobx-state-tree").IType<string | undefined, string, string>;
            regionInfo: import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>;
            path: import("mobx-state-tree").IType<string | undefined, string, string>;
            schemaPath: import("mobx-state-tree").IType<string | undefined, string, string>;
            region: import("mobx-state-tree").IType<string | undefined, string, string>;
            preferTag: import("mobx-state-tree").IType<string | undefined, string, string>;
            state: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IType<any, any, any>, [undefined]>;
            widthMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            heightMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            memberIndex: import("mobx-state-tree").IType<number | undefined, number, number>;
            folded: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            patched: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            x: import("mobx-state-tree").IType<number | undefined, number, number>;
            y: import("mobx-state-tree").IType<number | undefined, number, number>;
            w: import("mobx-state-tree").IType<number | undefined, number, number>;
            h: import("mobx-state-tree").IType<number | undefined, number, number>;
            dialogTitle: import("mobx-state-tree").IType<string | undefined, string, string>;
            dialogType: import("mobx-state-tree").IType<string | undefined, string, string>;
            children: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>;
        }, {
            getData: import("mobx-state-tree").IType<() => any, () => any, () => any>;
        } & {
            readonly info: RendererInfo;
            getNodeById(id: string, regionOrType?: string | undefined): any;
            setInfo(value: RendererInfo): void;
            updateSharedContext(value: Record<string, any>): void;
            readonly rendererConfig: import("amis-core").RendererConfig | undefined;
            setRendererConfig(value: import("amis-core").RendererConfig): void;
            readonly isVitualRenderer: boolean;
            readonly clickable: boolean;
            readonly draggable: boolean;
            readonly moveable: boolean;
            readonly canMoveUp: boolean;
            readonly canMoveDown: boolean;
            readonly removable: boolean;
            readonly duplicatable: boolean;
            readonly replaceable: boolean;
            memberImmutable(region: string): boolean;
            readonly isRegion: boolean;
            readonly childRegions: any[];
            readonly uniqueChildren: any[];
            readonly sameIdChild: any;
            readonly singleRegion: boolean;
            isExists(id: string): boolean;
            getChildById(id: string): any;
            readonly parent: any;
            readonly ancestorField: any;
            readonly host: any;
            readonly firstChild: any;
            readonly index: any;
            readonly prevSibling: any;
            readonly nextSibling: any;
            readonly schema: any;
            readonly schemaParent: any;
            readonly isSecondFactor: boolean;
        }, import("mobx-state-tree")._NotCustomized, import("mobx-state-tree")._NotCustomized>>;
        updateIsCommonConfig: (value: boolean) => void;
        addChild(props: {
            id: string;
            type: string;
            label: string;
            path: string;
            isCommonConfig?: boolean | undefined;
            info?: RendererInfo | undefined;
            region?: string | undefined;
            getData?: (() => any) | undefined;
            preferTag?: string | undefined;
            schemaPath?: string | undefined;
            dialogTitle?: string | undefined;
            dialogType?: string | undefined;
            regionInfo?: RegionConfig | undefined;
            widthMutable?: boolean | undefined;
            memberIndex?: number | undefined;
        }): any;
        removeChild(child: any): void;
        toggleFold(e: React.MouseEvent<HTMLAnchorElement, MouseEvent>): void;
        patch(store: any, force?: boolean, setPatchInfo?: ((id: string, value: any) => void) | undefined): void;
        updateSchema(value: any): void;
        updateSchemaStyle(value: any): void;
        setComponent(value: any): void;
        getComponent(): any;
        calculateHighlightBox(root?: any): void;
        resetHighlightBox(root: any): void;
        updateState(state: any, replace?: boolean): void;
        setWidthMutable(value: any): void;
        setHeightMutable(value: any): void;
    } & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IModelType<{
        parentId: import("mobx-state-tree").IType<string | undefined, string, string>;
        parentRegion: import("mobx-state-tree").IType<string | undefined, string, string>;
        isCommonConfig: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
        id: import("mobx-state-tree").IType<string | undefined, string, string>;
        type: import("mobx-state-tree").IType<string | undefined, string, string>;
        label: import("mobx-state-tree").IType<string | undefined, string, string>;
        regionInfo: import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>;
        path: import("mobx-state-tree").IType<string | undefined, string, string>;
        schemaPath: import("mobx-state-tree").IType<string | undefined, string, string>;
        region: import("mobx-state-tree").IType<string | undefined, string, string>;
        preferTag: import("mobx-state-tree").IType<string | undefined, string, string>;
        state: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IType<any, any, any>, [undefined]>;
        widthMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
        heightMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
        memberIndex: import("mobx-state-tree").IType<number | undefined, number, number>;
        folded: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
        patched: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
        x: import("mobx-state-tree").IType<number | undefined, number, number>;
        y: import("mobx-state-tree").IType<number | undefined, number, number>;
        w: import("mobx-state-tree").IType<number | undefined, number, number>;
        h: import("mobx-state-tree").IType<number | undefined, number, number>;
        dialogTitle: import("mobx-state-tree").IType<string | undefined, string, string>;
        dialogType: import("mobx-state-tree").IType<string | undefined, string, string>;
        children: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>;
    }, {
        getData: import("mobx-state-tree").IType<() => any, () => any, () => any>;
    } & {
        readonly info: RendererInfo;
        getNodeById(id: string, regionOrType?: string | undefined): any;
        setInfo(value: RendererInfo): void;
        updateSharedContext(value: Record<string, any>): void;
        readonly rendererConfig: import("amis-core").RendererConfig | undefined;
        setRendererConfig(value: import("amis-core").RendererConfig): void;
        readonly isVitualRenderer: boolean;
        readonly clickable: boolean;
        readonly draggable: boolean;
        readonly moveable: boolean;
        readonly canMoveUp: boolean;
        readonly canMoveDown: boolean;
        readonly removable: boolean;
        readonly duplicatable: boolean;
        readonly replaceable: boolean;
        memberImmutable(region: string): boolean;
        readonly isRegion: boolean;
        readonly childRegions: any[];
        readonly uniqueChildren: any[];
        readonly sameIdChild: any;
        readonly singleRegion: boolean;
        isExists(id: string): boolean;
        getChildById(id: string): any;
        readonly parent: any;
        readonly ancestorField: any;
        readonly host: any;
        readonly firstChild: any;
        readonly index: any;
        readonly prevSibling: any;
        readonly nextSibling: any;
        readonly schema: any;
        readonly schemaParent: any;
        readonly isSecondFactor: boolean;
    } & {
        getClosestParentByType: (type: string) => void | ({
            parentId: string;
            parentRegion: string;
            isCommonConfig: boolean;
            id: string;
            type: string;
            label: string;
            regionInfo: (RegionConfig & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>>) | undefined;
            path: string;
            schemaPath: string;
            region: string;
            preferTag: string;
            state: any;
            widthMutable: boolean;
            heightMutable: boolean;
            memberIndex: number;
            folded: boolean;
            patched: boolean;
            x: number;
            y: number;
            w: number;
            h: number;
            dialogTitle: string;
            dialogType: string;
            children: import("mobx-state-tree").IMSTArray<import("mobx-state-tree").IAnyModelType> & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>>;
        } & import("mobx-state-tree/dist/internal").NonEmptyObject & {
            getData: import("mobx-state-tree").IType<() => any, () => any, () => any>;
        } & {
            readonly info: RendererInfo;
            getNodeById(id: string, regionOrType?: string | undefined): any;
            setInfo(value: RendererInfo): void;
            updateSharedContext(value: Record<string, any>): void;
            readonly rendererConfig: import("amis-core").RendererConfig | undefined;
            setRendererConfig(value: import("amis-core").RendererConfig): void;
            readonly isVitualRenderer: boolean;
            readonly clickable: boolean;
            readonly draggable: boolean;
            readonly moveable: boolean;
            readonly canMoveUp: boolean;
            readonly canMoveDown: boolean;
            readonly removable: boolean;
            readonly duplicatable: boolean;
            readonly replaceable: boolean;
            memberImmutable(region: string): boolean;
            readonly isRegion: boolean;
            readonly childRegions: any[];
            readonly uniqueChildren: any[];
            readonly sameIdChild: any;
            readonly singleRegion: boolean;
            isExists(id: string): boolean;
            getChildById(id: string): any;
            readonly parent: any;
            readonly ancestorField: any;
            readonly host: any;
            readonly firstChild: any;
            readonly index: any;
            readonly prevSibling: any;
            readonly nextSibling: any;
            readonly schema: any;
            readonly schemaParent: any;
            readonly isSecondFactor: boolean;
        } & any & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IModelType<{
            parentId: import("mobx-state-tree").IType<string | undefined, string, string>;
            parentRegion: import("mobx-state-tree").IType<string | undefined, string, string>;
            isCommonConfig: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            id: import("mobx-state-tree").IType<string | undefined, string, string>;
            type: import("mobx-state-tree").IType<string | undefined, string, string>;
            label: import("mobx-state-tree").IType<string | undefined, string, string>;
            regionInfo: import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>;
            path: import("mobx-state-tree").IType<string | undefined, string, string>;
            schemaPath: import("mobx-state-tree").IType<string | undefined, string, string>;
            region: import("mobx-state-tree").IType<string | undefined, string, string>;
            preferTag: import("mobx-state-tree").IType<string | undefined, string, string>;
            state: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IType<any, any, any>, [undefined]>;
            widthMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            heightMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            memberIndex: import("mobx-state-tree").IType<number | undefined, number, number>;
            folded: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            patched: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            x: import("mobx-state-tree").IType<number | undefined, number, number>;
            y: import("mobx-state-tree").IType<number | undefined, number, number>;
            w: import("mobx-state-tree").IType<number | undefined, number, number>;
            h: import("mobx-state-tree").IType<number | undefined, number, number>;
            dialogTitle: import("mobx-state-tree").IType<string | undefined, string, string>;
            dialogType: import("mobx-state-tree").IType<string | undefined, string, string>;
            children: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>;
        }, {
            getData: import("mobx-state-tree").IType<() => any, () => any, () => any>;
        } & {
            readonly info: RendererInfo;
            getNodeById(id: string, regionOrType?: string | undefined): any;
            setInfo(value: RendererInfo): void;
            updateSharedContext(value: Record<string, any>): void;
            readonly rendererConfig: import("amis-core").RendererConfig | undefined;
            setRendererConfig(value: import("amis-core").RendererConfig): void;
            readonly isVitualRenderer: boolean;
            readonly clickable: boolean;
            readonly draggable: boolean;
            readonly moveable: boolean;
            readonly canMoveUp: boolean;
            readonly canMoveDown: boolean;
            readonly removable: boolean;
            readonly duplicatable: boolean;
            readonly replaceable: boolean;
            memberImmutable(region: string): boolean;
            readonly isRegion: boolean;
            readonly childRegions: any[];
            readonly uniqueChildren: any[];
            readonly sameIdChild: any;
            readonly singleRegion: boolean;
            isExists(id: string): boolean;
            getChildById(id: string): any;
            readonly parent: any;
            readonly ancestorField: any;
            readonly host: any;
            readonly firstChild: any;
            readonly index: any;
            readonly prevSibling: any;
            readonly nextSibling: any;
            readonly schema: any;
            readonly schemaParent: any;
            readonly isSecondFactor: boolean;
        } & any, import("mobx-state-tree")._NotCustomized, import("mobx-state-tree")._NotCustomized>>);
        getParentNodeByCB: (callback: (node: import("mobx-state-tree").ModelCreationType<import("mobx-state-tree/dist/internal").ExtractCFromProps<{
            parentId: import("mobx-state-tree").IType<string | undefined, string, string>;
            parentRegion: import("mobx-state-tree").IType<string | undefined, string, string>;
            isCommonConfig: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            id: import("mobx-state-tree").IType<string | undefined, string, string>;
            type: import("mobx-state-tree").IType<string | undefined, string, string>;
            label: import("mobx-state-tree").IType<string | undefined, string, string>;
            regionInfo: import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>;
            path: import("mobx-state-tree").IType<string | undefined, string, string>;
            schemaPath: import("mobx-state-tree").IType<string | undefined, string, string>;
            region: import("mobx-state-tree").IType<string | undefined, string, string>;
            preferTag: import("mobx-state-tree").IType<string | undefined, string, string>;
            state: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IType<any, any, any>, [undefined]>;
            widthMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            heightMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            memberIndex: import("mobx-state-tree").IType<number | undefined, number, number>;
            folded: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            patched: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            x: import("mobx-state-tree").IType<number | undefined, number, number>;
            y: import("mobx-state-tree").IType<number | undefined, number, number>;
            w: import("mobx-state-tree").IType<number | undefined, number, number>;
            h: import("mobx-state-tree").IType<number | undefined, number, number>;
            dialogTitle: import("mobx-state-tree").IType<string | undefined, string, string>;
            dialogType: import("mobx-state-tree").IType<string | undefined, string, string>;
            children: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>;
        }>>) => Boolean) => {
            parentId: string;
            parentRegion: string;
            isCommonConfig: boolean;
            id: string;
            type: string;
            label: string;
            regionInfo: (RegionConfig & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>>) | undefined;
            path: string;
            schemaPath: string;
            region: string;
            preferTag: string;
            state: any;
            widthMutable: boolean;
            heightMutable: boolean;
            memberIndex: number;
            folded: boolean;
            patched: boolean;
            x: number;
            y: number;
            w: number;
            h: number;
            dialogTitle: string;
            dialogType: string;
            children: import("mobx-state-tree").IMSTArray<import("mobx-state-tree").IAnyModelType> & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>>;
        } & import("mobx-state-tree/dist/internal").NonEmptyObject & {
            getData: import("mobx-state-tree").IType<() => any, () => any, () => any>;
        } & {
            readonly info: RendererInfo;
            getNodeById(id: string, regionOrType?: string | undefined): any;
            setInfo(value: RendererInfo): void;
            updateSharedContext(value: Record<string, any>): void;
            readonly rendererConfig: import("amis-core").RendererConfig | undefined;
            setRendererConfig(value: import("amis-core").RendererConfig): void;
            readonly isVitualRenderer: boolean;
            readonly clickable: boolean;
            readonly draggable: boolean;
            readonly moveable: boolean;
            readonly canMoveUp: boolean;
            readonly canMoveDown: boolean;
            readonly removable: boolean;
            readonly duplicatable: boolean;
            readonly replaceable: boolean;
            memberImmutable(region: string): boolean;
            readonly isRegion: boolean;
            readonly childRegions: any[];
            readonly uniqueChildren: any[];
            readonly sameIdChild: any;
            readonly singleRegion: boolean;
            isExists(id: string): boolean;
            getChildById(id: string): any;
            readonly parent: any;
            readonly ancestorField: any;
            readonly host: any;
            readonly firstChild: any;
            readonly index: any;
            readonly prevSibling: any;
            readonly nextSibling: any;
            readonly schema: any;
            readonly schemaParent: any;
            readonly isSecondFactor: boolean;
        } & import("mobx-state-tree").IStateTreeNode<import("mobx-state-tree").IModelType<{
            parentId: import("mobx-state-tree").IType<string | undefined, string, string>;
            parentRegion: import("mobx-state-tree").IType<string | undefined, string, string>;
            isCommonConfig: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            id: import("mobx-state-tree").IType<string | undefined, string, string>;
            type: import("mobx-state-tree").IType<string | undefined, string, string>;
            label: import("mobx-state-tree").IType<string | undefined, string, string>;
            regionInfo: import("mobx-state-tree").IMaybe<import("mobx-state-tree").IType<RegionConfig, RegionConfig, RegionConfig>>;
            path: import("mobx-state-tree").IType<string | undefined, string, string>;
            schemaPath: import("mobx-state-tree").IType<string | undefined, string, string>;
            region: import("mobx-state-tree").IType<string | undefined, string, string>;
            preferTag: import("mobx-state-tree").IType<string | undefined, string, string>;
            state: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IType<any, any, any>, [undefined]>;
            widthMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            heightMutable: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            memberIndex: import("mobx-state-tree").IType<number | undefined, number, number>;
            folded: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            patched: import("mobx-state-tree").IType<boolean | undefined, boolean, boolean>;
            x: import("mobx-state-tree").IType<number | undefined, number, number>;
            y: import("mobx-state-tree").IType<number | undefined, number, number>;
            w: import("mobx-state-tree").IType<number | undefined, number, number>;
            h: import("mobx-state-tree").IType<number | undefined, number, number>;
            dialogTitle: import("mobx-state-tree").IType<string | undefined, string, string>;
            dialogType: import("mobx-state-tree").IType<string | undefined, string, string>;
            children: import("mobx-state-tree").IOptionalIType<import("mobx-state-tree").IArrayType<import("mobx-state-tree").IAnyModelType>, [undefined]>;
        }, {
            getData: import("mobx-state-tree").IType<() => any, () => any, () => any>;
        } & {
            readonly info: RendererInfo;
            getNodeById(id: string, regionOrType?: string | undefined): any;
            setInfo(value: RendererInfo): void;
            updateSharedContext(value: Record<string, any>): void;
            readonly rendererConfig: import("amis-core").RendererConfig | undefined;
            setRendererConfig(value: import("amis-core").RendererConfig): void;
            readonly isVitualRenderer: boolean;
            readonly clickable: boolean;
            readonly draggable: boolean;
            readonly moveable: boolean;
            readonly canMoveUp: boolean;
            readonly canMoveDown: boolean;
            readonly removable: boolean;
            readonly duplicatable: boolean;
            readonly replaceable: boolean;
            memberImmutable(region: string): boolean;
            readonly isRegion: boolean;
            readonly childRegions: any[];
            readonly uniqueChildren: any[];
            readonly sameIdChild: any;
            readonly singleRegion: boolean;
            isExists(id: string): boolean;
            getChildById(id: string): any;
            readonly parent: any;
            readonly ancestorField: any;
            readonly host: any;
            readonly firstChild: any;
            readonly index: any;
            readonly prevSibling: any;
            readonly nextSibling: any;
            readonly schema: any;
            readonly schemaParent: any;
            readonly isSecondFactor: boolean;
        }, import("mobx-state-tree")._NotCustomized, import("mobx-state-tree")._NotCustomized>>;
        updateIsCommonConfig: (value: boolean) => void;
        addChild(props: {
            id: string;
            type: string;
            label: string;
            path: string;
            isCommonConfig?: boolean | undefined;
            info?: RendererInfo | undefined;
            region?: string | undefined;
            getData?: (() => any) | undefined;
            preferTag?: string | undefined;
            schemaPath?: string | undefined;
            dialogTitle?: string | undefined;
            dialogType?: string | undefined;
            regionInfo?: RegionConfig | undefined;
            widthMutable?: boolean | undefined;
            memberIndex?: number | undefined;
        }): any;
        removeChild(child: any): void;
        toggleFold(e: React.MouseEvent<HTMLAnchorElement, MouseEvent>): void;
        patch(store: any, force?: boolean, setPatchInfo?: ((id: string, value: any) => void) | undefined): void;
        updateSchema(value: any): void;
        updateSchemaStyle(value: any): void;
        setComponent(value: any): void;
        getComponent(): any;
        calculateHighlightBox(root?: any): void;
        resetHighlightBox(root: any): void;
        updateState(state: any, replace?: boolean): void;
        setWidthMutable(value: any): void;
        setHeightMutable(value: any): void;
    }, import("mobx-state-tree")._NotCustomized, import("mobx-state-tree")._NotCustomized>>) | null>;
    parentNode: EditorNodeType;
    editorNode: EditorNodeType;
    UNSAFE_componentWillMount(): void;
    componentDidMount(): void;
    componentDidUpdate(prevProps: RegionWrapperProps): void;
    componentWillUnmount(): void;
    /**
     * 弄点标记
     */
    markDom(id: string, region: string, rendererName?: string): void;
    render(): React.JSX.Element;
}
