import { CT_AreaChart } from '../../../../openxml/ChartTypes';
import { Workbook } from '../../../Workbook';
export declare function fromAreaChart(workbook: Workbook, areaChart: CT_AreaChart): {
    categories: string[];
    series: {
        name: string;
        type: string;
        stack: string | undefined;
        data: number[];
        label: {
            show?: boolean | undefined;
            position?: string | any[] | undefined;
            distance?: number | undefined;
            rotate?: number | undefined;
            offset?: any[] | undefined;
            formatter?: string | Function | undefined;
            color?: string | undefined;
            fontStyle?: string | undefined;
            fontWeight?: string | number | undefined;
            fontFamily?: string | undefined;
            fontSize?: number | undefined;
            align?: string | undefined;
            verticalAlign?: string | undefined;
            lineHeight?: number | undefined;
            backgroundColor?: string | object | undefined;
            borderColor?: string | undefined;
            borderWidth?: number | undefined;
            borderRadius?: number | undefined;
            padding?: number | any[] | undefined;
            shadowColor?: string | undefined;
            shadowBlur?: number | undefined;
            shadowOffsetX?: number | undefined;
            shadowOffsetY?: number | undefined;
            width?: string | number | undefined;
            height?: string | number | undefined;
            textBorderColor?: string | undefined;
            textBorderWidth?: number | undefined;
            textShadowColor?: string | undefined;
            textShadowBlur?: number | undefined;
            textShadowOffsetX?: number | undefined;
            textShadowOffsetY?: number | undefined;
            rich?: {
                [userStyle: string]: {
                    color?: string | undefined;
                    fontStyle?: string | undefined;
                    fontWeight?: string | number | undefined;
                    fontFamily?: string | undefined;
                    fontSize?: number | undefined;
                    align?: string | undefined;
                    verticalAlign?: string | undefined;
                    lineHeight?: number | undefined;
                    backgroundColor?: string | object | undefined;
                    borderColor?: string | undefined;
                    borderWidth?: number | undefined;
                    borderRadius?: number | undefined;
                    padding?: number | any[] | undefined;
                    shadowColor?: string | undefined;
                    shadowBlur?: number | undefined;
                    shadowOffsetX?: number | undefined;
                    shadowOffsetY?: number | undefined;
                    width?: string | number | undefined;
                    height?: string | number | undefined;
                    textBorderColor?: string | undefined;
                    textBorderWidth?: number | undefined;
                    textShadowColor?: string | undefined;
                    textShadowBlur?: number | undefined;
                    textShadowOffsetX?: number | undefined;
                    textShadowOffsetY?: number | undefined;
                };
            } | undefined;
        } | undefined;
        areaStyle: {};
    }[];
};
