/** generated by genIcons.ts, do not edit */
export declare const Icons: {
    filter: string;
    filterDown: string;
    filterUp: string;
    hasFilter: string;
    left: string;
    menu: string;
    plus: string;
    right: string;
    sortDown: string;
    sortUP: string;
};
